### ISSUE TITLE
Add icon for external links

### ISSUE THREAD

**Issue by dadarkfather** [njabulosibiya/website#11]
For all links that take user out of the website, the external link icon should be added to those links so user may know that they are about to be redirected to another website. I believe this will be useful in the project description where other sources are cited.

example:
https://codepen.io/fazlurr/pen/ExZdBp

**Comment by njabulosibiya** [comment]
Yeah, that's actually a good idea, although I wouldn't say it's that important but it does add to the navigation a bit.

**Comment by njabulosibiya** [comment]
The way to resolve this issue is simply to just add an icon next to the text. You can simply copy any button class icon code and replace icon class to 
> class = "uil uil-external-link-alt"

there's no need to make this a whole issue.
